Quang editable client profile
SamanthaGuillemette/SOEN390 pull request #209
Opened 2022-03-08 04:35 UTC by QuangTran304

These are the changes I made on this branch:

- Create `userInfoSlice` to store all the user info (name, dob, address, etc. ) in a single storage. Anyone wants to access to these properties can access from anywhere.
- Update `ClientProfile` component. Every fields are now editable & updatable.
- Added some small CSS.

2022-03-08 04:38 UTC, QuangTran304 commented on Client-app/src/components/SignIn/index.js
> -  console.log(inputLabelClasses);
Deleted this line for weird effect I found last time.

2022-03-10 22:53 UTC, MarwaKhalid commented
A few notes:
1. When I try to update from the edit modal, no data in the database gets changed
2. Clicking the update button does not close the modal
3. Branch has conflicts

2022-03-10 23:40 UTC, SamanthaGuillemette requested changes
The code looks good,  but for some reason the when I tested in local env the update button doesn't update the info. Can you check that please @QuangTran304

2022-03-13 03:43 UTC, QuangTran304 commented
> The code looks good, but for some reason the when I tested in local env the update button doesn't update the info. Can you check that please @QuangTran304

Sam, this should be fixed now. It happened before because I manually created the "profileImage" field on my client account from the Firebase backend (I forgot to handle the case where there's no such field in a new account). That's why I never saw the error but all of you do 😁 .

2022-03-13 15:30 UTC, QuangTran304 commented on Client-app/src/components/ClientProfile/ProfileEditModal.js
> +    window.location.reload();
Auto-refresh the page after user submits the updates.

2022-03-13 15:30 UTC, QuangTran304 commented on Client-app/src/components/ClientProfile/ClientProfile.test.js
> -  render(<ClientProfile />);
I commented this unit test body out to make it pass because the component needs access on Redux store (the <Provider /> component) inside its test.

2022-03-13 22:02 UTC, SamanthaGuillemette approved these changes
All works!

2022-03-13 22:06 UTC, merged